repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        # See https://pre-commit.com/hooks.html for more hooks
        - id: check-ast
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: debug-statements
        - id: end-of-file-fixer
        - id: name-tests-test
        - id: trailing-whitespace
        - id: requirements-txt-fixer

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort
          language_version: python3.12

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
        - id: black
          language_version: python3.12
          args: ["--line-length=99"]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        - id: flake8
          language_version: python3.12
          additional_dependencies: ['flake8-bugbear', 'flake8-comprehensions']

    # Also done in Makefile
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.5.1
    #   hooks:
    #     - id: mypy
    #       additional_dependencies: [
    #         'pandas-stubs',
    #       ]
    #       args: [
    #         '--ignore-missing-imports',
    #         '--disallow-untyped-defs',
    #         '--check-untyped-defs',
    #         '--warn-redundant-casts',
    #         '--warn-unused-ignores',
    #         '--warn-return-any',
    #         '--strict-optional',
    #         '--no-strict-optional',
    #       ]

    - repo: local
      hooks:
        - id: pytest
          name: pytest
          entry: pytest
          language: system
          pass_filenames: false
          always_run: true
